### PR TITLE
Fix windows pipeline speed

### PR DESCRIPTION
**Pull request by anotherbugmaster**
Dramatically increased analyzation speed.

### CODE REVIEW

**Comment by anotherbugmaster** [comment]
I think that CI is broken, guys.

**Comment by anotherbugmaster** [comment]
This should solve the #11 and #14 issues.

**Comment by alexanderpanchenko** [comment]
Thank you! LGTM. I will keep the #11 and #14 until users explicitly report that the perfomance issues were fixed.

**Comment by anotherbugmaster** [comment]
To be fair, I'm not so sure that this worked out exactly as I expected. I managed to increase performance on my setup with this fix and joining multiple strings with `". ".join(strings)`. Performance of analyzing an iterable of strings is the same as before.

**Comment by alexanderpanchenko** [comment]
ok. i will reopen it then.

**Pull request merged**
